DjangoProject/Authapp/urls.py
from django.urls import path, include
from Authapp import views

app_name = 'Authapp'
urlpatterns = [
    path('login/',views.login_page, name='login_page'),
    path('registeration',views.registeration,name='registeration'),
]

DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from Authapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('log_out/', views.log_out, name='log_out'),
    path('authapp/', include('Authapp.urls'))
]

DjangoProject/Authapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #creating using already existing user and adding extra fields to this user model
    Portfolio = models.URLField(blank=True)
    profile_pics = models.ImageField(upload_to='profile_pics', blank=True)
    

DjangoProject/Authapp/forms.py
from django import forms
from Authapp.models import UserInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields={'username','email','password'}

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = {'profile_pics','Portfolio'}

DjangoProject/Authapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from Authapp.forms import UserForm, UserInfoForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'Authapp/index.html')


def registeration(request):
    registered = False
    userform = UserForm
    userinfoform = UserInfoForm
    if request.method == 'POST':
        userform = UserForm(data=request.POST)
        userinfoform = UserInfoForm(data=request.POST)

        if userform.is_valid() and userinfoform.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            profile = userinfoform.save(commit=False)
            profile.user = user
            registered = True

            if 'profile_pics' in request.FILES:
                profile.profile_pics = request.FILES['profile_pics']
                profile.save()
    else:
        userform = UserForm()
        userinfoform = UserInfoForm()

    return render(request,'Authapp/registeration.html', {'userform':userform,
                                                         'userinfoform':userinfoform,
                                                         'registered':registered})

def login_page(request):

    if request.method == 'POST':
        password = request.POST.get('password')
        username = request.POST.get('username')

        user = authenticate(username=username,password=password)

        if  user:
            login(request,user)

            return HttpResponseRedirect(reverse('index'))
        else:
            print('some tried to hack')
            return HttpResponse('fawk')

    return render(request,'Authapp/login_page.html')



def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

DjangoProject/templates/Authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <!-- Navbar content -->
            <a class="navbar-brand" href="{% url 'index' %}">
              <img src="{% static 'images/logo.png' %}" width="50" height="50" alt="" loading="lazy"/>
            </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Authapp:registeration' %}">registeration</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'log_out' %}">Log out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Authapp:login_page' %}">Login</a>
              </li>
              {% endif %}

            </ul>
          </div>
        </nav>
      {% block body_block %}

      {% endblock %}


    </div>

  </body>
</html>

DjangoProject/templates/Authapp/index.html
{% extends 'Authapp/base.html' %}
{% load static %}


{% block body_block %}
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  <div class="jumbotron">
    <h1>home page</h1>

  </div>
{% endblock %}

DjangoProject/templates/Authapp/login_page.html
{% extends 'Authapp/base.html' %}

{% block body_block %}
  <div class="jumbotron">
    <h1>login page</h1>
    <form class="" action="{% url 'Authapp:login_page' %}" method="post">
      {% csrf_token %}
      <label for="email">username: </label>
      <input type="text" name="username" palaceholder="username">
      <label for="password">Password: </label>
      <input type="text" name="password" placeholder="password">
      <input type="submit" name="" value="Login">

    </form>

  </div>
{% endblock %}

DjangoProject/templates/Authapp/registeration.html
{% extends 'Authapp/base.html' %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
    <h1>thank you for registration</h1>
    <h3>now, you can easily login</h3>
    {% else %}
    <h1>Please register to use our site with full access</h1>
    <form method="post">
      {% csrf_token %}
      {{ userform.as_p }}
      {{ userinfoform.as_p }}
      <input type="submit" name="" value="register me">
    </form>
    {% endif %}


  </div>
{% endblock %}